// Version 4
export const questions = [
  {
    question: "What is an onlay restoration?",
    options: ["A restoration that does not cover any cusps", "An indirect restoration that covers one or more cusps", "A direct restoration placed intraorally", "A restoration only for anterior teeth"],
    answer: 1
  },
  {
    question: "What is an indication for indirect restorations related to accessibility?",
    options: ["Easy accessibility", "Lack of accessibility", "Always accessible", "Only for anterior teeth"],
    answer: 1
  },
  {
    question: "What standard of oral hygiene is required for indirect restorations?",
    options: ["Poor oral hygiene", "Fair oral hygiene", "Good standard of oral hygiene", "No hygiene needed"],
    answer: 2
  },
  {
    question: "Why should cavities be free from marked undercuts for indirect restorations?",
    options: ["Because undercuts improve retention", "Because cavities must be free from marked undercuts", "Because undercuts are necessary", "Because undercuts are easy to restore"],
    answer: 1
  },
  {
    question: "What is a contraindication related to subgingival margins?",
    options: ["Supragingival margins", "Deep subgingival preparations because margins are difficult to record and finish", "Margins at the gumline", "Enamel margins"],
    answer: 1
  },
  {
    question: "What is a challenge when achieving proper interproximal contact with direct composites?",
    options: ["Excessive contact", "Achievement of proper interproximal contact and complete cure in deepest regions", "No contact needed", "Only occlusal contact matters"],
    answer: 1
  },
  {
    question: "What goals are achieved through the post-polymerization phase of indirect composites?",
    options: ["Increased polymerization shrinkage", "High conversion rate and improved mechanical and optical properties", "Weaker material", "Reduced fitness of restorations"],
    answer: 1
  },
  {
    question: "What happens to internal stress generated by polymerization shrinkage with near 100% conversion?",
    options: ["It increases", "It is reduced with appreciably improved fitness of restorations", "It remains the same", "It causes fracture"],
    answer: 1
  },
  {
    question: "What was the composition of first generation IRCs?",
    options: ["Different from direct composites", "Identical to that of the direct resin composite marketed by the same manufacturer", "Only metal based", "Only ceramic based"],
    answer: 1
  },
  {
    question: "What examples are given of first generation IRCs?",
    options: ["Artglass and belleGlass HP", "Visio-Gem, Dentacolor, SR Isosit inlay system, Coltene Brilliant, and Concept", "Only Solidex", "Only ceramic materials"],
    answer: 1
  },
  {
    question: "In second generation IRCs, the filler content was twice that of which component?",
    options: ["The ceramic matrix", "The organic matrix", "The metal reinforcement", "The glass matrix"],
    answer: 1
  },
  {
    question: "What are the three areas of improvement in second generation IRCs?",
    options: ["Color, cost, and availability", "Structure and composition, polymerization technique, and fiber reinforcement", "Size, weight, and packaging", "Only hardness and wear"],
    answer: 1
  },
  {
    question: "What types of ceramics are used for inlays and onlays?",
    options: ["Only feldspathic porcelain", "Feldspathic porcelain, hot pressed ceramics, and machinable ceramics for CAD/CAM", "Only machinable ceramics", "Only hot pressed ceramics"],
    answer: 1
  },
  {
    question: "What discovery about glasses in 1968 led to glass-ceramics?",
    options: ["They could not be modified", "Certain glasses could be modified with nucleating agents and changed into ceramics with organized crystalline forms", "They were too weak", "They had no dental use"],
    answer: 1
  },
  {
    question: "What factor might tip the balance of advantages toward composite inlay over ceramic inlay?",
    options: ["Lower hardness of composite", "Higher cost and difficulty of manufacturing ceramic inlay", "Better aesthetics of composite", "Composite is always stronger"],
    answer: 1
  }
];