export const lectureNames = {
    "endodontics": {
        "1": "Introduction",
        "2": "Classification Of Periapical Disease",
        "3": "Access Opening Preparation",
        "4": "Applications Of Radiography",
        "5": "Rubber Dam",
        "6": "Clean& Shape Root Canal",
        "7": "Clean& Shape Root Canal 2",
        "8": "Root Canal Obturation",
        "9": "Unknown",
        "10": "Unknown",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "Unknown",
        "30": "Unknown"
    },
    "generalmedicine": {
        "1": "Diabetes Mellitus",
        "2": "Management of DM",
        "3": "WBC disorders part 1",
        "4": "WBC Disorders part 2",
        "5": "bleeding disorders",
        "6": "Unknown",
        "7": "Unknown",
        "8": "Unknown",
        "9": "Unknown",
        "10": "Unknown",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "Unknown",
        "30": "Unknown"
    },
    "generalsurgery": {
        "1": "Metabolic response to injury",
        "2": "Wounds healing",
        "3": "Surgical wounds and infections",
        "4": "Hemorrhage and blood transfusion",
        "5": "Shock",
        "6": "Parenteral nutrition",
        "7": "Unknown",
        "8": "Unknown",
        "9": "test",
        "10": "Unknown",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "welcome",
        "30": "Unknown"
    },
    "operative": {
        "1": "Assessment, Diagnosis, Treatment Planning",
        "2": " Assessment, Diagnosis, Treatment Planning 2",
        "3": "Biologic Consideration of Enamel",
        "4": "Biologic Consideration of Dentin 1",
        "5": "Biologic Consideration of Dentin 2",
        "6": "Unknown",
        "7": "Unknown",
        "8": "Unknown",
        "9": "Unknown",
        "10": "Unknown",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "Unknown",
        "30": "Unknown"
    },
    "oralpathology": {
        "1": "Biopsy (Principles and techniques)",
        "2": "Dental caries",
        "3": "Disorders of dental pulp",
        "4": "Periapical Pathology",
        "5": "inflammatory diseases of bone",
        "6": "Fibro osseous Lesions",
        "7": "Giant cell lesions",
        "8": "Unknown",
        "9": "Unknown",
        "10": "Unknown",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "Unknown",
        "30": "Unknown"
    },
    "oralsurgery": {
        "1": "Hypertension",
        "2": "Heart failure",
        "3": "Infective endocarditis",
        "4": "Diabetes mellitus",
        "5": "Adrenal Insufficiency",
        "6": "Thyroid diseases",
        "7": "Unknown",
        "8": "bleeding disorder",
        "9": "Unknown",
        "10": "liver disease",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "Unknown",
        "30": "Unknown"
    },
    "orthodontics": {
        "1": "Introduction",
        "2": "andrew keys of normal occlusion",
        "3": "Iatrogenic effect of orthodontic treatment",
        "4": "Classification of Malocclusion",
        "5": "Etiology of malocclusion",
        "6": "G&D introduction",
        "7": "G&D Growth pattern, timing, variability",
        "8": "Unknown",
        "9": "Unknown",
        "10": "Unknown",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "Unknown",
        "30": "Unknown"
    },
    "pedodontics": {
        "1": "Teeth reuption",
        "2": "teeth numbering system",
        "3": "Dental caries",
        "4": "Rampant caries",
        "5": "Morphology of primary teeth",
        "6": "Unknown",
        "7": "Unknown",
        "8": "Unknown",
        "9": "Unknown",
        "10": "Unknown",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "Unknown",
        "30": "Unknown"
    },
    "periodontology": {
        "1": "Terms in periodontology",
        "2": "Periodontal ligament ",
        "3": "Cementum",
        "4": "Alveolar process",
        "5": "Classification of periodontal diseases 1",
        "6": "Classification of periodontal diseases 2",
        "7": "pathogenesis of periodontal disease",
        "8": "Unknown",
        "9": "Unknown",
        "10": "Unknown",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "Unknown",
        "30": "Unknown"
    },
    "prosthodontics": {
        "1": "Osteology",
        "2": "Myology",
        "3": "Diagnosis & Treatment Plan for RPD",
        "4": "Mouth Preparation for RPD",
        "5": "Impression for RPD",
        "6": "impression materials 2",
        "7": "support for Distal Extension base",
        "8": "Unknown",
        "9": "Unknown",
        "10": "Unknown",
        "11": "Unknown",
        "12": "Unknown",
        "13": "Unknown",
        "14": "Unknown",
        "15": "Unknown",
        "16": "Unknown",
        "17": "Unknown",
        "18": "Unknown",
        "19": "Unknown",
        "20": "Unknown",
        "21": "Unknown",
        "22": "Unknown",
        "23": "Unknown",
        "24": "Unknown",
        "25": "Unknown",
        "26": "Unknown",
        "27": "Unknown",
        "28": "Unknown",
        "29": "Unknown",
        "30": "Unknown"
    }
};