export const questions = [
  {
    question: "Which prenatal factor has been clearly implicated in congenital deformities such as cleft lip and palate?",
    options: [
      "Maternal uterine fibroids",
      "Amniotic lesions",
      "Maternal thalidomide intake during pregnancy",
      "Abnormal fetal posture and intrauterine pressure"
    ],
    answer: 2
  },
  {
    question: "Cervical headgear derives anchorage from?",
    options: [
      "Occipital region",
      "Maxillary first molars",
      "Back of the neck (cervical region)",
      "Frontal bone"
    ],
    answer: 2
  },
  {
    question: "A child with delayed tooth eruption, prolonged retention of deciduous teeth, and enamel hypoplasia most likely suffers from?",
    options: [
      "Hyperthyroidism",
      "Hypothyroidism",
      "Hypoparathyroidism",
      "Diabetes mellitus"
    ],
    answer: 1
  },
  {
    question: "Malocclusion from large tooth size from one parent and reduced jaw length from the other is explained by?",
    options: [
      "Dominant genetic inheritance",
      "Disharmonious genetic inheritance leading to arch length-tooth material discrepancy",
      "Recessive genetic mutation",
      "Environmental factors during development"
    ],
    answer: 1
  },
  {
    question: "Which histologic event characterizes direct (frontal) bone resorption during orthodontic tooth movement?",
    options: [
      "Osteoclastic resorption beneath hyalinized tissue",
      "Osteoblastic deposition on tension side",
      "Osteoclastic resorption of alveolar bone adjacent to the periodontal ligament",
      "Endosteal resorption from marrow spaces"
    ],
    answer: 2
  },
  {
    question: "Following application of light orthodontic forces, all changes occur on the pressure side EXCEPT?",
    options: [
      "Slight compression of periodontal ligament",
      "Dilatation of blood vessels",
      "Recruitment of osteoclasts",
      "Formation of extensive hyalinized zones"
    ],
    answer: 3
  },
  {
    question: "Hyalinization of the PDL is most accurately described as?",
    options: [
      "A reversible inflammatory response",
      "A fibrous hyperplasia of ligament tissue",
      "A sterile necrosis resulting from excessive compression of periodontal ligament",
      "A calcified tissue deposit"
    ],
    answer: 2
  },
  {
    question: "The lag phase of orthodontic tooth movement primarily results from?",
    options: [
      "Decreased osteoclast activity",
      "Increased osteoblast activity",
      "Presence of hyalinized tissue that must be removed before bone resorption can proceed",
      "Reduction in blood flow to the pulp"
    ],
    answer: 2
  },
  {
    question: "Vibratory stimulation accelerates orthodontic tooth movement because it?",
    options: [
      "Increases bone density around teeth",
      "Reduces inflammatory response",
      "Stimulates inflammatory mediators, thereby increasing tooth movement",
      "Directly mechanically displaces teeth"
    ],
    answer: 2
  },
  {
    question: "Which pairing correctly matches the medication with its stated effect on orthodontic tooth movement?",
    options: [
      "Bisphosphonates → accelerate via increased osteoclast activity",
      "Corticosteroids → decelerate via increased osteoblast function",
      "Corticosteroids → accelerate movement by increasing resorption but reduce stability",
      "Thyroxine → reduces movement by increasing bone density",
      "Estrogens → accelerate movement maximally during ovulation due to high hormone levels"
    ],
    answer: 2
  },
  {
    question: "Force = 50g, perpendicular distance to CR = 8mm. Moment of force (Mf) = ?",
    options: [
      "58 g·mm",
      "400 g",
      "400 g·mm",
      "6.25 g·mm"
    ],
    answer: 2
  },
  {
    question: "Single-rooted tooth with normal periodontal support has center of resistance located approximately:",
    options: [
      "At the CEJ",
      "At the root apex",
      "At the midpoint of the root",
      "At the crown center",
      "About 1/3 of the distance from the CEJ to the root apex"
    ],
    answer: 4
  },
  {
    question: "Uncontrolled tipping by a single force applied to the crown rotates the tooth about a center of rotation located:",
    options: [
      "At the center of resistance",
      "At the root apex",
      "Between the center of resistance and the root apex",
      "At the incisal edge",
      "At the alveolar crest"
    ],
    answer: 2
  },
  {
    question: "A 'pure moment' (rotation tendency without net translation) is generated by:",
    options: [
      "A single force applied at the crown",
      "A force applied at the center of resistance",
      "Two forces applied in the same direction",
      "A couple: two parallel equal and opposite forces separated by a distance",
      "A force applied at the root apex"
    ],
    answer: 3
  },
  {
    question: "Best example of a passive orthodontic appliance:",
    options: [
      "Active labial bow",
      "Screw expander",
      "Spring retractor",
      "Space maintainer/retainer used to maintain tooth position",
      "Elastic chain"
    ],
    answer: 3
  },
  {
    question: "Functional appliances differ from mechanical appliances because functional appliances:",
    options: [
      "Are always removable",
      "Are always fixed",
      "Utilize natural forces from orofacial/masticatory musculature and transmit them to teeth and/or jaws",
      "Generate active mechanical springs",
      "Only work in adult patients"
    ],
    answer: 2
  },
  {
    question: "Which statement reflects the biologic requirement related to anchorage?",
    options: [
      "The appliance should be simple in design",
      "The appliance should be durable",
      "The appliance should move only the intended teeth; anchor units should remain in their original position",
      "The appliance should be esthetically pleasing",
      "The appliance should be easy to clean"
    ],
    answer: 2
  },
  {
    question: "Which is a BIOLOGIC requirement of an ideal orthodontic appliance?",
    options: [
      "Simple in design",
      "Durable and strong",
      "Should not cause detrimental effects on teeth/periodontium",
      "Inconspicuous in appearance",
      "Easy to activate"
    ],
    answer: 2
  },
  {
    question: "Which tooth movement is CONTRAINDICATED for removable orthodontic appliances?",
    options: [
      "Tipping of incisors",
      "Correction of anterior crossbite in mixed dentition",
      "Bodily movement requiring three-dimensional root control",
      "Overbite reduction",
      "Space maintenance"
    ],
    answer: 2
  },
  {
    question: "Most critical factor limiting the effectiveness of removable orthodontic appliances:",
    options: [
      "Acrylic baseplate thickness",
      "Wire material used",
      "Patient compliance",
      "Number of clasps used",
      "Appliance cost"
    ],
    answer: 2
  },
  {
    question: "An anterior bite plane is primarily indicated for correction of:",
    options: [
      "Open bite",
      "Deep bite",
      "Crossbite",
      "Class III malocclusion",
      "Midline diastema"
    ],
    answer: 1
  },
  {
    question: "Primary mechanism by which anterior bite plane reduces overbite:",
    options: [
      "Intruding incisors",
      "Allowing posterior tooth eruption",
      "Extruding incisors",
      "Retracting incisors",
      "Intruding posterior teeth"
    ],
    answer: 1
  },
  {
    question: "Regarding micro-osteoperforation (MOP), which option matches the protocol and planned biological effect?",
    options: [
      "Requires periodontal flap surgery performed by a periodontist",
      "Screws are inserted and left in situ for 6 months",
      "Full-thickness flap is necessary for access",
      "Special screws are inserted through gingiva into interproximal alveolar bone and withdrawn",
      "Inhibits osteoclast activity to stabilize teeth"
    ],
    answer: 3
  },
  {
    question: "A fixed lingual bonded retainer is classified most appropriately as:",
    options: [
      "Active removable appliance",
      "Active fixed appliance",
      "Passive removable appliance",
      "Passive fixed appliance",
      "Functional appliance"
    ],
    answer: 3
  },
  {
    question: "Under 'active or passive' classification, which statement best defines an active appliance?",
    options: [
      "An appliance that holds teeth in position",
      "An appliance that maintains arch form",
      "An appliance that produces tooth movement, either by incorporating active forces",
      "An appliance that prevents relapse",
      "An appliance that is cemented permanently"
    ],
    answer: 2
  },
  {
    question: "Which statement best differentiates piezocision from corticotomy?",
    options: [
      "Piezocision requires full flap reflection",
      "Corticotomy uses facial gingival incisions only",
      "Piezocision uses both facial and lingual incisions",
      "Piezocision uses facial gingival incisions only, with bone injury created",
      "Corticotomy does not involve bone injury"
    ],
    answer: 3
  }
];