export const questions = [
  {
    question: "What is the definition of force in orthodontics?",
    options: ["Energy applied to bone", "Pressure on periodontal ligament", "Heat generated by appliance", "Load applied to object that tends to move it to different position"],
    answer: 3
  },
  {
    question: "In intrusion, what happens to the supporting structures?",
    options: ["Mixed pressure and tension", "Only tension", "No stress applied", "Whole structure under pressure with virtually no tension"],
    answer: 3
  },
  {
    question: "What causes undermining resorption?",
    options: ["No force applied", "Very light forces", "Continuous light forces", "Heavy magnitude intermittent forces"],
    answer: 3
  },
  {
    question: "Where is pressure distributed during bodily movement?",
    options: ["Only at the apex", "Only at cervical area", "Only at mid-root", "Evenly over whole PDL length"],
    answer: 3
  },
  {
    question: "Which movement is useful in Class II Division 2 cases requiring flaring?",
    options: ["Bodily movement", "Rotation", "Root torque", "Uncontrolled tipping"],
    answer: 3
  },
  {
    question: "Applying excessive force during intrusion will cause what?",
    options: ["Faster tooth movement", "Bone deposition", "No effect", "Root resorption"],
    answer: 3
  },
  {
    question: "What type of bone facilitates faster tooth movement?",
    options: ["Dense lamellated bone", "Cortical bone only", "Compact bone", "Loose cancellous bone with large marrow spaces"],
    answer: 3
  },
  {
    question: "For a symmetrical free body in vacuum, what is true about center of mass?",
    options: ["Different from center of resistance", "Does not exist", "Located at the surface", "Same as center of resistance"],
    answer: 3
  },
  {
    question: "What defines center of resistance for teeth?",
    options: ["Point of maximum stress", "Point where bracket is attached", "Point of bone contact", "Point where force application results in bodily movement"],
    answer: 3
  },
  {
    question: "Rotation can be achieved by removable appliance if rotation is less than what degree?",
    options: ["45 degrees", "60 degrees", "180 degrees", "90 degrees"],
    answer: 3
  },
  {
    question: "What is the optimum force for extrusion?",
    options: ["70-120 grams", "10-20 grams", "50-100 grams", "35-60 grams"],
    answer: 3
  },
  {
    question: "What is biomechanics?",
    options: ["Study of tooth anatomy", "Study of appliance design only", "Study of chemical reactions in body", "Study of mechanical aspects of biological systems using methods of mechanics"],
    answer: 3
  },
  {
    question: "When force is not acting through center of resistance, what is created?",
    options: ["Translation only", "No movement", "Extrusion", "Moment (tendency to rotate)"],
    answer: 3
  },
  {
    question: "Which factor does NOT affect location of center of resistance?",
    options: ["Root length", "Number of roots", "Alveolar bone level", "Tooth color"],
    answer: 3
  },
  {
    question: "What occurs during the repair phase between appliance activations?",
    options: ["Tooth stops moving permanently", "Bone becomes weaker", "Appliance loses all force", "PDL regeneration and repair"],
    answer: 3
  }
];
